import os
import sys
from pathlib import Path

import click
import jinja2
import yaml
from yaml.scanner import ScannerError

from docker_etl.file_utils import (
    CI_JOB_NAME,
    ROOT_DIR,
    find_file_in_jobs,
)

CI_DIR = os.path.join(ROOT_DIR, ".github")
CI_JOB_WORKFLOW_TEMPLATE = "job-workflow.template.yml"

CI_CONFIG_HEADER = """###
# This file was generated by docker-etl/ci_config.py.
# Changes should be made to .github/config.template.yml and re-generated.
###"""


def validate_yaml(yaml_path: Path) -> bool:
    """Load a yaml file and return the success of the parse."""
    with open(yaml_path) as f:
        try:
            yaml.safe_load(f)
        except ScannerError:
            return False
    return True


def update_config(dry_run: bool = False) -> str:
    """Generate individual GitHub Actions workflow files for each job."""
    template_loader = jinja2.FileSystemLoader(CI_DIR)
    template_env = jinja2.Environment(loader=template_loader)
    workflow_template = template_env.get_template(CI_JOB_WORKFLOW_TEMPLATE)

    job_configs = sorted(find_file_in_jobs(CI_JOB_NAME))

    invalid_configs = [
        str(conf.relative_to(ROOT_DIR))
        for conf in job_configs
        if not validate_yaml(conf)
    ]
    if len(invalid_configs) > 0:
        print("Error: Invalid job configs", file=sys.stderr)
        print("\n".join(invalid_configs), file=sys.stderr)
        sys.exit(1)

    workflows_dir = ROOT_DIR / ".github" / "workflows"
    generated_files = []

    for job_config_path in job_configs:
        # Extract job name from path (e.g., jobs/bq2sftp/ci_job.yaml -> bq2sftp)
        job_name = job_config_path.parent.name

        # Read the job config and remove path filter steps
        job_config_text = job_config_path.read_text()

        # Remove the path filter step from job config
        lines = job_config_text.split('\n')
        filtered_lines = []
        skip_until_next_step = False

        for line in lines:
            if '- name: Check if job files changed' in line:
                skip_until_next_step = True
                continue
            if skip_until_next_step:
                if line.strip().startswith('- name:'):
                    skip_until_next_step = False
                else:
                    continue
            # Remove 'if: steps.changes.outputs.job' lines
            if "if: steps.changes.outputs.job == 'true'" in line:
                continue
            filtered_lines.append(line)

        clean_job_config = '\n'.join(filtered_lines)

        # Generate workflow file
        workflow_text = workflow_template.render(
            job_name=job_name,
            job_config=clean_job_config,
        )

        workflow_filename = f"job-{job_name}.yml"

        if dry_run:
            print(f"=== {workflow_filename} ===")
            print(workflow_text)
            print()
        else:
            workflow_path = workflows_dir / workflow_filename
            with open(workflow_path, "w") as f:
                f.write(workflow_text)
            generated_files.append(workflow_filename)

    if not dry_run:
        print(f"Generated {len(generated_files)} workflow files:")
        for filename in generated_files:
            print(f"  - {filename}")

    return ""


@click.command()
@click.option(
    "--dry-run/--no-dry-run",
    default=False,
    help="Dry run will print to stdout instead of generating workflow files",
)
def main(dry_run: bool):
    update_config(dry_run)


if __name__ == "__main__":
    main()
