---
metric_hub:
  app_name: "firefox_desktop"
  slug: "daily_active_users_v2"
  alias: "DAU"
  start_date: "2023-05-13"
  end_date: NULL

forecast:
  model_type: "prophet"
  start_date: NULL
  end_date: NULL
  use_holidays: True
  parameters:
    changepoint_prior_scale: 0.05
    changepoint_range: 0.8
    seasonality_prior_scale: 0.01

summarize:
  periods: ["day", "month"]
  numpy_aggregations: ["mean"]
  quantiles: [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95]

output:
  project: "moz-fx-data-shared-prod"
  dataset: "telemetry_derived"
  models_table: "kpi_forecast_models"
  features_table: "kpi_forecast_metrics"
  predictions_table: "kpi_forecast_predictions"
