[all]
type = "unconditional"

[global_1000]
type = "site_reports_field"
host_min_ranks_condition = "MIN(global_rank) <= 1000"

[sightline]
type = "site_reports_field"
host_min_ranks_condition = "MIN(sightline_rank) <= 1000 OR MIN(global_rank) <= 1000"

[japan_1000]
type = "site_reports_field"
host_min_ranks_condition = "MIN(japan_rank) <= 1000"

[japan_1000_mobile]
type = "site_reports_field"
conditions = ["IFNULL(is_japan_1000, FALSE)", "is_mobile"]
