---
model_type: prophet
metric_hub:
  app_name: "multi_product"
  slug: "mobile_daily_active_users_v1"
  alias: "mobile_dau"
  start_date: "2021-02-01"
  end_date: NULL

forecast_model:
  forecast_start: NULL
  forecast_end: NULL
  predict_historical_dates: False
  parameters:
    seasonality_prior_scale: 0.01
    changepoint_prior_scale: 0.01
    weekly_seasonality: True
    yearly_seasonality: True
    use_all_us_holidays: True

summarize:
  periods: ["day", "month"]
  numpy_aggregations: ["mean"]
  percentiles: [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95]

write_results:
  project: "moz-fx-data-shared-prod"
  project_legacy: "moz-fx-data-shared-prod"
  dataset: "telemetry_derived"
  dataset_legacy: "telemetry_derived"
  table: "kpi_forecasts_v0"
  forecast_table_legacy: "kpi_automated_forecast_v1"
  confidences_table_legacy: "kpi_automated_forecast_confidences_v1"
