---
metric_hub:
  app_name: "multi_product"
  slug: "search_forecasting_revenue_per_ad_click"
  alias: "search_forecasting_revenue_per_ad_click"
  start_date: "2020-01-01"
  end_date: "last complete month"
  segments:
    device: "device"
    channel: "'all'"
    country: "CASE WHEN country = 'US' THEN 'US' ELSE 'ROW' END"
    partner: "partner"
  where: "partner = 'Google'"

forecast_model:
  model_type: "scalar"
  start_date: NULL
  end_date: NULL
  use_holidays: False
  parameters:
    adjustment_type: "YOY"

summarize:
  periods: ["year"]
  numpy_aggregations: ["mean"]

write_results:
  project: "moz-fx-data-shared-prod"
  dataset: "revenue_derived"
  table: "search_revenue_forecasts_v1"
  components_table: "search_revenue_model_components_v1"
